//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: HSAdminRefreshProtocol.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
//  refresh admin acls request.
type RefreshAdminAclsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAdminAclsRequestProto) Reset() {
	*x = RefreshAdminAclsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAdminAclsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminAclsRequestProto) ProtoMessage() {}

func (x *RefreshAdminAclsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminAclsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshAdminAclsRequestProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{0}
}

//*
// Response for refresh admin acls.
type RefreshAdminAclsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAdminAclsResponseProto) Reset() {
	*x = RefreshAdminAclsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAdminAclsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminAclsResponseProto) ProtoMessage() {}

func (x *RefreshAdminAclsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminAclsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshAdminAclsResponseProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{1}
}

//*
//  refresh loaded job cache request.
type RefreshLoadedJobCacheRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshLoadedJobCacheRequestProto) Reset() {
	*x = RefreshLoadedJobCacheRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshLoadedJobCacheRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLoadedJobCacheRequestProto) ProtoMessage() {}

func (x *RefreshLoadedJobCacheRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLoadedJobCacheRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshLoadedJobCacheRequestProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{2}
}

//*
// Response for refresh loaded job cache.
type RefreshLoadedJobCacheResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshLoadedJobCacheResponseProto) Reset() {
	*x = RefreshLoadedJobCacheResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshLoadedJobCacheResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLoadedJobCacheResponseProto) ProtoMessage() {}

func (x *RefreshLoadedJobCacheResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLoadedJobCacheResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshLoadedJobCacheResponseProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{3}
}

//*
//  refresh job retention settings request.
type RefreshJobRetentionSettingsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshJobRetentionSettingsRequestProto) Reset() {
	*x = RefreshJobRetentionSettingsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshJobRetentionSettingsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshJobRetentionSettingsRequestProto) ProtoMessage() {}

func (x *RefreshJobRetentionSettingsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshJobRetentionSettingsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshJobRetentionSettingsRequestProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{4}
}

//*
// Response for refresh job retention.
type RefreshJobRetentionSettingsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshJobRetentionSettingsResponseProto) Reset() {
	*x = RefreshJobRetentionSettingsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshJobRetentionSettingsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshJobRetentionSettingsResponseProto) ProtoMessage() {}

func (x *RefreshJobRetentionSettingsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshJobRetentionSettingsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshJobRetentionSettingsResponseProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{5}
}

//
//  refresh log retention request.
type RefreshLogRetentionSettingsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshLogRetentionSettingsRequestProto) Reset() {
	*x = RefreshLogRetentionSettingsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshLogRetentionSettingsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLogRetentionSettingsRequestProto) ProtoMessage() {}

func (x *RefreshLogRetentionSettingsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLogRetentionSettingsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshLogRetentionSettingsRequestProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{6}
}

//*
// Response for refresh log retention.
type RefreshLogRetentionSettingsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshLogRetentionSettingsResponseProto) Reset() {
	*x = RefreshLogRetentionSettingsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HSAdminRefreshProtocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshLogRetentionSettingsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLogRetentionSettingsResponseProto) ProtoMessage() {}

func (x *RefreshLogRetentionSettingsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HSAdminRefreshProtocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLogRetentionSettingsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshLogRetentionSettingsResponseProto) Descriptor() ([]byte, []int) {
	return file_HSAdminRefreshProtocol_proto_rawDescGZIP(), []int{7}
}

var File_HSAdminRefreshProtocol_proto protoreflect.FileDescriptor

var file_HSAdminRefreshProtocol_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x48, 0x53, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x23, 0x0a, 0x21, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x22, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x27,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x28, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x27, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a,
	0x0a, 0x28, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x74, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xc7, 0x04, 0x0a, 0x1d, 0x48,
	0x53, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x10,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x63, 0x6c, 0x73,
	0x12, 0x2e, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x2f, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x82, 0x01, 0x0a, 0x15, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f, 0x61,
	0x64, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x33, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x34, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x94, 0x01, 0x0a, 0x1b, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x39, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x3a, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x94, 0x01,
	0x0a, 0x1b, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x74, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x39, 0x2e,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x74, 0x65, 0x6e,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3a, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f,
	0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x42, 0x82, 0x01, 0x0a, 0x27, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x68, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x42, 0x1c, 0x48, 0x53, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x33,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d, 0x30, 0x30,
	0x35, 0x35, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x72, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_HSAdminRefreshProtocol_proto_rawDescOnce sync.Once
	file_HSAdminRefreshProtocol_proto_rawDescData = file_HSAdminRefreshProtocol_proto_rawDesc
)

func file_HSAdminRefreshProtocol_proto_rawDescGZIP() []byte {
	file_HSAdminRefreshProtocol_proto_rawDescOnce.Do(func() {
		file_HSAdminRefreshProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_HSAdminRefreshProtocol_proto_rawDescData)
	})
	return file_HSAdminRefreshProtocol_proto_rawDescData
}

var file_HSAdminRefreshProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_HSAdminRefreshProtocol_proto_goTypes = []interface{}{
	(*RefreshAdminAclsRequestProto)(nil),             // 0: hadoop.mapreduce.RefreshAdminAclsRequestProto
	(*RefreshAdminAclsResponseProto)(nil),            // 1: hadoop.mapreduce.RefreshAdminAclsResponseProto
	(*RefreshLoadedJobCacheRequestProto)(nil),        // 2: hadoop.mapreduce.RefreshLoadedJobCacheRequestProto
	(*RefreshLoadedJobCacheResponseProto)(nil),       // 3: hadoop.mapreduce.RefreshLoadedJobCacheResponseProto
	(*RefreshJobRetentionSettingsRequestProto)(nil),  // 4: hadoop.mapreduce.RefreshJobRetentionSettingsRequestProto
	(*RefreshJobRetentionSettingsResponseProto)(nil), // 5: hadoop.mapreduce.RefreshJobRetentionSettingsResponseProto
	(*RefreshLogRetentionSettingsRequestProto)(nil),  // 6: hadoop.mapreduce.RefreshLogRetentionSettingsRequestProto
	(*RefreshLogRetentionSettingsResponseProto)(nil), // 7: hadoop.mapreduce.RefreshLogRetentionSettingsResponseProto
}
var file_HSAdminRefreshProtocol_proto_depIdxs = []int32{
	0, // 0: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshAdminAcls:input_type -> hadoop.mapreduce.RefreshAdminAclsRequestProto
	2, // 1: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshLoadedJobCache:input_type -> hadoop.mapreduce.RefreshLoadedJobCacheRequestProto
	4, // 2: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshJobRetentionSettings:input_type -> hadoop.mapreduce.RefreshJobRetentionSettingsRequestProto
	6, // 3: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshLogRetentionSettings:input_type -> hadoop.mapreduce.RefreshLogRetentionSettingsRequestProto
	1, // 4: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshAdminAcls:output_type -> hadoop.mapreduce.RefreshAdminAclsResponseProto
	3, // 5: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshLoadedJobCache:output_type -> hadoop.mapreduce.RefreshLoadedJobCacheResponseProto
	5, // 6: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshJobRetentionSettings:output_type -> hadoop.mapreduce.RefreshJobRetentionSettingsResponseProto
	7, // 7: hadoop.mapreduce.HSAdminRefreshProtocolService.refreshLogRetentionSettings:output_type -> hadoop.mapreduce.RefreshLogRetentionSettingsResponseProto
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HSAdminRefreshProtocol_proto_init() }
func file_HSAdminRefreshProtocol_proto_init() {
	if File_HSAdminRefreshProtocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HSAdminRefreshProtocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAdminAclsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HSAdminRefreshProtocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAdminAclsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HSAdminRefreshProtocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshLoadedJobCacheRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HSAdminRefreshProtocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshLoadedJobCacheResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HSAdminRefreshProtocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshJobRetentionSettingsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HSAdminRefreshProtocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshJobRetentionSettingsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HSAdminRefreshProtocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshLogRetentionSettingsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HSAdminRefreshProtocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshLogRetentionSettingsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HSAdminRefreshProtocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_HSAdminRefreshProtocol_proto_goTypes,
		DependencyIndexes: file_HSAdminRefreshProtocol_proto_depIdxs,
		MessageInfos:      file_HSAdminRefreshProtocol_proto_msgTypes,
	}.Build()
	File_HSAdminRefreshProtocol_proto = out.File
	file_HSAdminRefreshProtocol_proto_rawDesc = nil
	file_HSAdminRefreshProtocol_proto_goTypes = nil
	file_HSAdminRefreshProtocol_proto_depIdxs = nil
}
