//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: mr_service_protos.proto

package common

import (
	_ "github.com/kom0055/go-hadoop/proto/common"
	_ "github.com/kom0055/go-hadoop/proto/yarn/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobReportRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (x *GetJobReportRequestProto) Reset() {
	*x = GetJobReportRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobReportRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobReportRequestProto) ProtoMessage() {}

func (x *GetJobReportRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobReportRequestProto.ProtoReflect.Descriptor instead.
func (*GetJobReportRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobReportRequestProto) GetJobId() *JobIdProto {
	if x != nil {
		return x.JobId
	}
	return nil
}

type GetJobReportResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobReport *JobReportProto `protobuf:"bytes,1,opt,name=job_report,json=jobReport" json:"job_report,omitempty"`
}

func (x *GetJobReportResponseProto) Reset() {
	*x = GetJobReportResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobReportResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobReportResponseProto) ProtoMessage() {}

func (x *GetJobReportResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobReportResponseProto.ProtoReflect.Descriptor instead.
func (*GetJobReportResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobReportResponseProto) GetJobReport() *JobReportProto {
	if x != nil {
		return x.JobReport
	}
	return nil
}

type GetTaskReportRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId *TaskIdProto `protobuf:"bytes,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (x *GetTaskReportRequestProto) Reset() {
	*x = GetTaskReportRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskReportRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReportRequestProto) ProtoMessage() {}

func (x *GetTaskReportRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReportRequestProto.ProtoReflect.Descriptor instead.
func (*GetTaskReportRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskReportRequestProto) GetTaskId() *TaskIdProto {
	if x != nil {
		return x.TaskId
	}
	return nil
}

type GetTaskReportResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskReport *TaskReportProto `protobuf:"bytes,1,opt,name=task_report,json=taskReport" json:"task_report,omitempty"`
}

func (x *GetTaskReportResponseProto) Reset() {
	*x = GetTaskReportResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskReportResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReportResponseProto) ProtoMessage() {}

func (x *GetTaskReportResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReportResponseProto.ProtoReflect.Descriptor instead.
func (*GetTaskReportResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskReportResponseProto) GetTaskReport() *TaskReportProto {
	if x != nil {
		return x.TaskReport
	}
	return nil
}

type GetTaskAttemptReportRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskAttemptId *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
}

func (x *GetTaskAttemptReportRequestProto) Reset() {
	*x = GetTaskAttemptReportRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskAttemptReportRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskAttemptReportRequestProto) ProtoMessage() {}

func (x *GetTaskAttemptReportRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskAttemptReportRequestProto.ProtoReflect.Descriptor instead.
func (*GetTaskAttemptReportRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskAttemptReportRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if x != nil {
		return x.TaskAttemptId
	}
	return nil
}

type GetTaskAttemptReportResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskAttemptReport *TaskAttemptReportProto `protobuf:"bytes,1,opt,name=task_attempt_report,json=taskAttemptReport" json:"task_attempt_report,omitempty"`
}

func (x *GetTaskAttemptReportResponseProto) Reset() {
	*x = GetTaskAttemptReportResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskAttemptReportResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskAttemptReportResponseProto) ProtoMessage() {}

func (x *GetTaskAttemptReportResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskAttemptReportResponseProto.ProtoReflect.Descriptor instead.
func (*GetTaskAttemptReportResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskAttemptReportResponseProto) GetTaskAttemptReport() *TaskAttemptReportProto {
	if x != nil {
		return x.TaskAttemptReport
	}
	return nil
}

type GetCountersRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (x *GetCountersRequestProto) Reset() {
	*x = GetCountersRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountersRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountersRequestProto) ProtoMessage() {}

func (x *GetCountersRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountersRequestProto.ProtoReflect.Descriptor instead.
func (*GetCountersRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{6}
}

func (x *GetCountersRequestProto) GetJobId() *JobIdProto {
	if x != nil {
		return x.JobId
	}
	return nil
}

type GetCountersResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counters *CountersProto `protobuf:"bytes,1,opt,name=counters" json:"counters,omitempty"`
}

func (x *GetCountersResponseProto) Reset() {
	*x = GetCountersResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountersResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountersResponseProto) ProtoMessage() {}

func (x *GetCountersResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountersResponseProto.ProtoReflect.Descriptor instead.
func (*GetCountersResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{7}
}

func (x *GetCountersResponseProto) GetCounters() *CountersProto {
	if x != nil {
		return x.Counters
	}
	return nil
}

type GetTaskAttemptCompletionEventsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	FromEventId *int32      `protobuf:"varint,2,opt,name=from_event_id,json=fromEventId" json:"from_event_id,omitempty"`
	MaxEvents   *int32      `protobuf:"varint,3,opt,name=max_events,json=maxEvents" json:"max_events,omitempty"`
}

func (x *GetTaskAttemptCompletionEventsRequestProto) Reset() {
	*x = GetTaskAttemptCompletionEventsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskAttemptCompletionEventsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskAttemptCompletionEventsRequestProto) ProtoMessage() {}

func (x *GetTaskAttemptCompletionEventsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskAttemptCompletionEventsRequestProto.ProtoReflect.Descriptor instead.
func (*GetTaskAttemptCompletionEventsRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskAttemptCompletionEventsRequestProto) GetJobId() *JobIdProto {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *GetTaskAttemptCompletionEventsRequestProto) GetFromEventId() int32 {
	if x != nil && x.FromEventId != nil {
		return *x.FromEventId
	}
	return 0
}

func (x *GetTaskAttemptCompletionEventsRequestProto) GetMaxEvents() int32 {
	if x != nil && x.MaxEvents != nil {
		return *x.MaxEvents
	}
	return 0
}

type GetTaskAttemptCompletionEventsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompletionEvents []*TaskAttemptCompletionEventProto `protobuf:"bytes,1,rep,name=completion_events,json=completionEvents" json:"completion_events,omitempty"`
}

func (x *GetTaskAttemptCompletionEventsResponseProto) Reset() {
	*x = GetTaskAttemptCompletionEventsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskAttemptCompletionEventsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskAttemptCompletionEventsResponseProto) ProtoMessage() {}

func (x *GetTaskAttemptCompletionEventsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskAttemptCompletionEventsResponseProto.ProtoReflect.Descriptor instead.
func (*GetTaskAttemptCompletionEventsResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskAttemptCompletionEventsResponseProto) GetCompletionEvents() []*TaskAttemptCompletionEventProto {
	if x != nil {
		return x.CompletionEvents
	}
	return nil
}

type GetTaskReportsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId    *JobIdProto    `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	TaskType *TaskTypeProto `protobuf:"varint,2,opt,name=task_type,json=taskType,enum=hadoop.mapreduce.TaskTypeProto" json:"task_type,omitempty"`
}

func (x *GetTaskReportsRequestProto) Reset() {
	*x = GetTaskReportsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskReportsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReportsRequestProto) ProtoMessage() {}

func (x *GetTaskReportsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReportsRequestProto.ProtoReflect.Descriptor instead.
func (*GetTaskReportsRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskReportsRequestProto) GetJobId() *JobIdProto {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *GetTaskReportsRequestProto) GetTaskType() TaskTypeProto {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return TaskTypeProto_MAP
}

type GetTaskReportsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskReports []*TaskReportProto `protobuf:"bytes,1,rep,name=task_reports,json=taskReports" json:"task_reports,omitempty"`
}

func (x *GetTaskReportsResponseProto) Reset() {
	*x = GetTaskReportsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskReportsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReportsResponseProto) ProtoMessage() {}

func (x *GetTaskReportsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReportsResponseProto.ProtoReflect.Descriptor instead.
func (*GetTaskReportsResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskReportsResponseProto) GetTaskReports() []*TaskReportProto {
	if x != nil {
		return x.TaskReports
	}
	return nil
}

type GetDiagnosticsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskAttemptId *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
}

func (x *GetDiagnosticsRequestProto) Reset() {
	*x = GetDiagnosticsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiagnosticsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsRequestProto) ProtoMessage() {}

func (x *GetDiagnosticsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsRequestProto.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{12}
}

func (x *GetDiagnosticsRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if x != nil {
		return x.TaskAttemptId
	}
	return nil
}

type GetDiagnosticsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []string `protobuf:"bytes,1,rep,name=diagnostics" json:"diagnostics,omitempty"`
}

func (x *GetDiagnosticsResponseProto) Reset() {
	*x = GetDiagnosticsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiagnosticsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsResponseProto) ProtoMessage() {}

func (x *GetDiagnosticsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsResponseProto.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{13}
}

func (x *GetDiagnosticsResponseProto) GetDiagnostics() []string {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type KillJobRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId *JobIdProto `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (x *KillJobRequestProto) Reset() {
	*x = KillJobRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillJobRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillJobRequestProto) ProtoMessage() {}

func (x *KillJobRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillJobRequestProto.ProtoReflect.Descriptor instead.
func (*KillJobRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{14}
}

func (x *KillJobRequestProto) GetJobId() *JobIdProto {
	if x != nil {
		return x.JobId
	}
	return nil
}

type KillJobResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KillJobResponseProto) Reset() {
	*x = KillJobResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillJobResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillJobResponseProto) ProtoMessage() {}

func (x *KillJobResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillJobResponseProto.ProtoReflect.Descriptor instead.
func (*KillJobResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{15}
}

type KillTaskRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId *TaskIdProto `protobuf:"bytes,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (x *KillTaskRequestProto) Reset() {
	*x = KillTaskRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillTaskRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTaskRequestProto) ProtoMessage() {}

func (x *KillTaskRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTaskRequestProto.ProtoReflect.Descriptor instead.
func (*KillTaskRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{16}
}

func (x *KillTaskRequestProto) GetTaskId() *TaskIdProto {
	if x != nil {
		return x.TaskId
	}
	return nil
}

type KillTaskResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KillTaskResponseProto) Reset() {
	*x = KillTaskResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillTaskResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTaskResponseProto) ProtoMessage() {}

func (x *KillTaskResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTaskResponseProto.ProtoReflect.Descriptor instead.
func (*KillTaskResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{17}
}

type KillTaskAttemptRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskAttemptId *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
}

func (x *KillTaskAttemptRequestProto) Reset() {
	*x = KillTaskAttemptRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillTaskAttemptRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTaskAttemptRequestProto) ProtoMessage() {}

func (x *KillTaskAttemptRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTaskAttemptRequestProto.ProtoReflect.Descriptor instead.
func (*KillTaskAttemptRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{18}
}

func (x *KillTaskAttemptRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if x != nil {
		return x.TaskAttemptId
	}
	return nil
}

type KillTaskAttemptResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KillTaskAttemptResponseProto) Reset() {
	*x = KillTaskAttemptResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillTaskAttemptResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTaskAttemptResponseProto) ProtoMessage() {}

func (x *KillTaskAttemptResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTaskAttemptResponseProto.ProtoReflect.Descriptor instead.
func (*KillTaskAttemptResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{19}
}

type FailTaskAttemptRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskAttemptId *TaskAttemptIdProto `protobuf:"bytes,1,opt,name=task_attempt_id,json=taskAttemptId" json:"task_attempt_id,omitempty"`
}

func (x *FailTaskAttemptRequestProto) Reset() {
	*x = FailTaskAttemptRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailTaskAttemptRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTaskAttemptRequestProto) ProtoMessage() {}

func (x *FailTaskAttemptRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTaskAttemptRequestProto.ProtoReflect.Descriptor instead.
func (*FailTaskAttemptRequestProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{20}
}

func (x *FailTaskAttemptRequestProto) GetTaskAttemptId() *TaskAttemptIdProto {
	if x != nil {
		return x.TaskAttemptId
	}
	return nil
}

type FailTaskAttemptResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FailTaskAttemptResponseProto) Reset() {
	*x = FailTaskAttemptResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mr_service_protos_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailTaskAttemptResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTaskAttemptResponseProto) ProtoMessage() {}

func (x *FailTaskAttemptResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_mr_service_protos_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTaskAttemptResponseProto.ProtoReflect.Descriptor instead.
func (*FailTaskAttemptResponseProto) Descriptor() ([]byte, []int) {
	return file_mr_service_protos_proto_rawDescGZIP(), []int{21}
}

var File_mr_service_protos_proto protoreflect.FileDescriptor

var file_mr_service_protos_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x68, 0x61, 0x64, 0x6f, 0x6f,
	0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x1a, 0x0e, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6d, 0x72, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x79, 0x61,
	0x72, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x33, 0x0a, 0x06, 0x6a,
	0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x4a,
	0x6f, 0x62, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64,
	0x22, 0x5c, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3f, 0x0a,
	0x0a, 0x6a, 0x6f, 0x62, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x53,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x36, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68,
	0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x42, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x70, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4c, 0x0a, 0x0f, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x41, 0x74,
	0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x22, 0x7d, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x58, 0x0a, 0x13,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x68, 0x61, 0x64, 0x6f,
	0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x11, 0x74, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x4e, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x33, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x3b, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61,
	0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22,
	0xa4, 0x01, 0x0a, 0x2a, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x33,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x6a, 0x6f,
	0x62, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x2b, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x5e, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x33, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d,
	0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x09, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08,
	0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x63, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x44, 0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x6a, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4c, 0x0a, 0x0f, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61,
	0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0d, 0x74, 0x61, 0x73, 0x6b,
	0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x4a, 0x0a, 0x13, 0x4b, 0x69,
	0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x33, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x4b, 0x69, 0x6c, 0x6c, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e,
	0x0a, 0x14, 0x4b, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x36, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70,
	0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x17,
	0x0a, 0x15, 0x4b, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x1b, 0x4b, 0x69, 0x6c, 0x6c, 0x54,
	0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4c, 0x0a, 0x0f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x61,
	0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x4b, 0x69, 0x6c, 0x6c, 0x54, 0x61, 0x73, 0x6b,
	0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x1b, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x61, 0x73, 0x6b,
	0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x4c, 0x0a, 0x0f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x68,
	0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49,
	0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x42, 0x72, 0x0a, 0x24, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2e, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0f, 0x4d, 0x52, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2f, 0x67,
	0x6f, 0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x72, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_mr_service_protos_proto_rawDescOnce sync.Once
	file_mr_service_protos_proto_rawDescData = file_mr_service_protos_proto_rawDesc
)

func file_mr_service_protos_proto_rawDescGZIP() []byte {
	file_mr_service_protos_proto_rawDescOnce.Do(func() {
		file_mr_service_protos_proto_rawDescData = protoimpl.X.CompressGZIP(file_mr_service_protos_proto_rawDescData)
	})
	return file_mr_service_protos_proto_rawDescData
}

var file_mr_service_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_mr_service_protos_proto_goTypes = []interface{}{
	(*GetJobReportRequestProto)(nil),                    // 0: hadoop.mapreduce.GetJobReportRequestProto
	(*GetJobReportResponseProto)(nil),                   // 1: hadoop.mapreduce.GetJobReportResponseProto
	(*GetTaskReportRequestProto)(nil),                   // 2: hadoop.mapreduce.GetTaskReportRequestProto
	(*GetTaskReportResponseProto)(nil),                  // 3: hadoop.mapreduce.GetTaskReportResponseProto
	(*GetTaskAttemptReportRequestProto)(nil),            // 4: hadoop.mapreduce.GetTaskAttemptReportRequestProto
	(*GetTaskAttemptReportResponseProto)(nil),           // 5: hadoop.mapreduce.GetTaskAttemptReportResponseProto
	(*GetCountersRequestProto)(nil),                     // 6: hadoop.mapreduce.GetCountersRequestProto
	(*GetCountersResponseProto)(nil),                    // 7: hadoop.mapreduce.GetCountersResponseProto
	(*GetTaskAttemptCompletionEventsRequestProto)(nil),  // 8: hadoop.mapreduce.GetTaskAttemptCompletionEventsRequestProto
	(*GetTaskAttemptCompletionEventsResponseProto)(nil), // 9: hadoop.mapreduce.GetTaskAttemptCompletionEventsResponseProto
	(*GetTaskReportsRequestProto)(nil),                  // 10: hadoop.mapreduce.GetTaskReportsRequestProto
	(*GetTaskReportsResponseProto)(nil),                 // 11: hadoop.mapreduce.GetTaskReportsResponseProto
	(*GetDiagnosticsRequestProto)(nil),                  // 12: hadoop.mapreduce.GetDiagnosticsRequestProto
	(*GetDiagnosticsResponseProto)(nil),                 // 13: hadoop.mapreduce.GetDiagnosticsResponseProto
	(*KillJobRequestProto)(nil),                         // 14: hadoop.mapreduce.KillJobRequestProto
	(*KillJobResponseProto)(nil),                        // 15: hadoop.mapreduce.KillJobResponseProto
	(*KillTaskRequestProto)(nil),                        // 16: hadoop.mapreduce.KillTaskRequestProto
	(*KillTaskResponseProto)(nil),                       // 17: hadoop.mapreduce.KillTaskResponseProto
	(*KillTaskAttemptRequestProto)(nil),                 // 18: hadoop.mapreduce.KillTaskAttemptRequestProto
	(*KillTaskAttemptResponseProto)(nil),                // 19: hadoop.mapreduce.KillTaskAttemptResponseProto
	(*FailTaskAttemptRequestProto)(nil),                 // 20: hadoop.mapreduce.FailTaskAttemptRequestProto
	(*FailTaskAttemptResponseProto)(nil),                // 21: hadoop.mapreduce.FailTaskAttemptResponseProto
	(*JobIdProto)(nil),                                  // 22: hadoop.mapreduce.JobIdProto
	(*JobReportProto)(nil),                              // 23: hadoop.mapreduce.JobReportProto
	(*TaskIdProto)(nil),                                 // 24: hadoop.mapreduce.TaskIdProto
	(*TaskReportProto)(nil),                             // 25: hadoop.mapreduce.TaskReportProto
	(*TaskAttemptIdProto)(nil),                          // 26: hadoop.mapreduce.TaskAttemptIdProto
	(*TaskAttemptReportProto)(nil),                      // 27: hadoop.mapreduce.TaskAttemptReportProto
	(*CountersProto)(nil),                               // 28: hadoop.mapreduce.CountersProto
	(*TaskAttemptCompletionEventProto)(nil),             // 29: hadoop.mapreduce.TaskAttemptCompletionEventProto
	(TaskTypeProto)(0),                                  // 30: hadoop.mapreduce.TaskTypeProto
}
var file_mr_service_protos_proto_depIdxs = []int32{
	22, // 0: hadoop.mapreduce.GetJobReportRequestProto.job_id:type_name -> hadoop.mapreduce.JobIdProto
	23, // 1: hadoop.mapreduce.GetJobReportResponseProto.job_report:type_name -> hadoop.mapreduce.JobReportProto
	24, // 2: hadoop.mapreduce.GetTaskReportRequestProto.task_id:type_name -> hadoop.mapreduce.TaskIdProto
	25, // 3: hadoop.mapreduce.GetTaskReportResponseProto.task_report:type_name -> hadoop.mapreduce.TaskReportProto
	26, // 4: hadoop.mapreduce.GetTaskAttemptReportRequestProto.task_attempt_id:type_name -> hadoop.mapreduce.TaskAttemptIdProto
	27, // 5: hadoop.mapreduce.GetTaskAttemptReportResponseProto.task_attempt_report:type_name -> hadoop.mapreduce.TaskAttemptReportProto
	22, // 6: hadoop.mapreduce.GetCountersRequestProto.job_id:type_name -> hadoop.mapreduce.JobIdProto
	28, // 7: hadoop.mapreduce.GetCountersResponseProto.counters:type_name -> hadoop.mapreduce.CountersProto
	22, // 8: hadoop.mapreduce.GetTaskAttemptCompletionEventsRequestProto.job_id:type_name -> hadoop.mapreduce.JobIdProto
	29, // 9: hadoop.mapreduce.GetTaskAttemptCompletionEventsResponseProto.completion_events:type_name -> hadoop.mapreduce.TaskAttemptCompletionEventProto
	22, // 10: hadoop.mapreduce.GetTaskReportsRequestProto.job_id:type_name -> hadoop.mapreduce.JobIdProto
	30, // 11: hadoop.mapreduce.GetTaskReportsRequestProto.task_type:type_name -> hadoop.mapreduce.TaskTypeProto
	25, // 12: hadoop.mapreduce.GetTaskReportsResponseProto.task_reports:type_name -> hadoop.mapreduce.TaskReportProto
	26, // 13: hadoop.mapreduce.GetDiagnosticsRequestProto.task_attempt_id:type_name -> hadoop.mapreduce.TaskAttemptIdProto
	22, // 14: hadoop.mapreduce.KillJobRequestProto.job_id:type_name -> hadoop.mapreduce.JobIdProto
	24, // 15: hadoop.mapreduce.KillTaskRequestProto.task_id:type_name -> hadoop.mapreduce.TaskIdProto
	26, // 16: hadoop.mapreduce.KillTaskAttemptRequestProto.task_attempt_id:type_name -> hadoop.mapreduce.TaskAttemptIdProto
	26, // 17: hadoop.mapreduce.FailTaskAttemptRequestProto.task_attempt_id:type_name -> hadoop.mapreduce.TaskAttemptIdProto
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_mr_service_protos_proto_init() }
func file_mr_service_protos_proto_init() {
	if File_mr_service_protos_proto != nil {
		return
	}
	file_mr_protos_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mr_service_protos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobReportRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobReportResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskReportRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskReportResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskAttemptReportRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskAttemptReportResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountersRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountersResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskAttemptCompletionEventsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskAttemptCompletionEventsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskReportsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskReportsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiagnosticsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiagnosticsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillJobRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillJobResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillTaskRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillTaskResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillTaskAttemptRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillTaskAttemptResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailTaskAttemptRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mr_service_protos_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailTaskAttemptResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mr_service_protos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mr_service_protos_proto_goTypes,
		DependencyIndexes: file_mr_service_protos_proto_depIdxs,
		MessageInfos:      file_mr_service_protos_proto_msgTypes,
	}.Build()
	File_mr_service_protos_proto = out.File
	file_mr_service_protos_proto_rawDesc = nil
	file_mr_service_protos_proto_goTypes = nil
	file_mr_service_protos_proto_depIdxs = nil
}
