//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: github.com/kom0055/go-hadoop/proto/v1alpha1/yarn/server/nm/yarn_server_nodemanager_recovery.proto

package nm

import (
	api "github.com/kom0055/go-hadoop/proto/v1alpha1/yarn/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerManagerApplicationProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                          *api.ApplicationIdProto         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	User                        *string                         `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Credentials                 []byte                          `protobuf:"bytes,3,opt,name=credentials" json:"credentials,omitempty"`
	Acls                        []*api.ApplicationACLMapProto   `protobuf:"bytes,4,rep,name=acls" json:"acls,omitempty"`
	LogAggregationContext       *api.LogAggregationContextProto `protobuf:"bytes,5,opt,name=log_aggregation_context,json=logAggregationContext" json:"log_aggregation_context,omitempty"`
	AppLogAggregationInitedTime *int64                          `protobuf:"varint,6,opt,name=appLogAggregationInitedTime,def=-1" json:"appLogAggregationInitedTime,omitempty"`
	FlowContext                 *FlowContextProto               `protobuf:"bytes,7,opt,name=flowContext" json:"flowContext,omitempty"`
}

// Default values for ContainerManagerApplicationProto fields.
const (
	Default_ContainerManagerApplicationProto_AppLogAggregationInitedTime = int64(-1)
)

func (x *ContainerManagerApplicationProto) Reset() {
	*x = ContainerManagerApplicationProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerManagerApplicationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerManagerApplicationProto) ProtoMessage() {}

func (x *ContainerManagerApplicationProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerManagerApplicationProto.ProtoReflect.Descriptor instead.
func (*ContainerManagerApplicationProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerManagerApplicationProto) GetId() *api.ApplicationIdProto {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ContainerManagerApplicationProto) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *ContainerManagerApplicationProto) GetCredentials() []byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ContainerManagerApplicationProto) GetAcls() []*api.ApplicationACLMapProto {
	if x != nil {
		return x.Acls
	}
	return nil
}

func (x *ContainerManagerApplicationProto) GetLogAggregationContext() *api.LogAggregationContextProto {
	if x != nil {
		return x.LogAggregationContext
	}
	return nil
}

func (x *ContainerManagerApplicationProto) GetAppLogAggregationInitedTime() int64 {
	if x != nil && x.AppLogAggregationInitedTime != nil {
		return *x.AppLogAggregationInitedTime
	}
	return Default_ContainerManagerApplicationProto_AppLogAggregationInitedTime
}

func (x *ContainerManagerApplicationProto) GetFlowContext() *FlowContextProto {
	if x != nil {
		return x.FlowContext
	}
	return nil
}

type DeletionServiceDeleteTaskProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	User              *string  `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Subdir            *string  `protobuf:"bytes,3,opt,name=subdir" json:"subdir,omitempty"`
	DeletionTime      *int64   `protobuf:"varint,4,opt,name=deletionTime" json:"deletionTime,omitempty"`
	Basedirs          []string `protobuf:"bytes,5,rep,name=basedirs" json:"basedirs,omitempty"`
	SuccessorIds      []int32  `protobuf:"varint,6,rep,name=successorIds" json:"successorIds,omitempty"`
	TaskType          *string  `protobuf:"bytes,7,opt,name=taskType" json:"taskType,omitempty"`
	DockerContainerId *string  `protobuf:"bytes,8,opt,name=dockerContainerId" json:"dockerContainerId,omitempty"`
}

func (x *DeletionServiceDeleteTaskProto) Reset() {
	*x = DeletionServiceDeleteTaskProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletionServiceDeleteTaskProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionServiceDeleteTaskProto) ProtoMessage() {}

func (x *DeletionServiceDeleteTaskProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionServiceDeleteTaskProto.ProtoReflect.Descriptor instead.
func (*DeletionServiceDeleteTaskProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *DeletionServiceDeleteTaskProto) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *DeletionServiceDeleteTaskProto) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *DeletionServiceDeleteTaskProto) GetSubdir() string {
	if x != nil && x.Subdir != nil {
		return *x.Subdir
	}
	return ""
}

func (x *DeletionServiceDeleteTaskProto) GetDeletionTime() int64 {
	if x != nil && x.DeletionTime != nil {
		return *x.DeletionTime
	}
	return 0
}

func (x *DeletionServiceDeleteTaskProto) GetBasedirs() []string {
	if x != nil {
		return x.Basedirs
	}
	return nil
}

func (x *DeletionServiceDeleteTaskProto) GetSuccessorIds() []int32 {
	if x != nil {
		return x.SuccessorIds
	}
	return nil
}

func (x *DeletionServiceDeleteTaskProto) GetTaskType() string {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return ""
}

func (x *DeletionServiceDeleteTaskProto) GetDockerContainerId() string {
	if x != nil && x.DockerContainerId != nil {
		return *x.DockerContainerId
	}
	return ""
}

type LocalizedResourceProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource  *api.LocalResourceProto `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	LocalPath *string                 `protobuf:"bytes,2,opt,name=localPath" json:"localPath,omitempty"`
	Size      *int64                  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (x *LocalizedResourceProto) Reset() {
	*x = LocalizedResourceProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalizedResourceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedResourceProto) ProtoMessage() {}

func (x *LocalizedResourceProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedResourceProto.ProtoReflect.Descriptor instead.
func (*LocalizedResourceProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *LocalizedResourceProto) GetResource() *api.LocalResourceProto {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *LocalizedResourceProto) GetLocalPath() string {
	if x != nil && x.LocalPath != nil {
		return *x.LocalPath
	}
	return ""
}

func (x *LocalizedResourceProto) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type LogDeleterProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	DeletionTime *int64  `protobuf:"varint,2,opt,name=deletionTime" json:"deletionTime,omitempty"`
}

func (x *LogDeleterProto) Reset() {
	*x = LogDeleterProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogDeleterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogDeleterProto) ProtoMessage() {}

func (x *LogDeleterProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogDeleterProto.ProtoReflect.Descriptor instead.
func (*LogDeleterProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *LogDeleterProto) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *LogDeleterProto) GetDeletionTime() int64 {
	if x != nil && x.DeletionTime != nil {
		return *x.DeletionTime
	}
	return 0
}

type FlowContextProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowName    *string `protobuf:"bytes,1,opt,name=flowName" json:"flowName,omitempty"`
	FlowVersion *string `protobuf:"bytes,2,opt,name=flowVersion" json:"flowVersion,omitempty"`
	FlowRunId   *int64  `protobuf:"varint,3,opt,name=flowRunId" json:"flowRunId,omitempty"`
}

func (x *FlowContextProto) Reset() {
	*x = FlowContextProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowContextProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowContextProto) ProtoMessage() {}

func (x *FlowContextProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowContextProto.ProtoReflect.Descriptor instead.
func (*FlowContextProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescGZIP(), []int{4}
}

func (x *FlowContextProto) GetFlowName() string {
	if x != nil && x.FlowName != nil {
		return *x.FlowName
	}
	return ""
}

func (x *FlowContextProto) GetFlowVersion() string {
	if x != nil && x.FlowVersion != nil {
		return *x.FlowVersion
	}
	return ""
}

func (x *FlowContextProto) GetFlowRunId() int64 {
	if x != nil && x.FlowRunId != nil {
		return *x.FlowRunId
	}
	return 0
}

var File_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto protoreflect.FileDescriptor

var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDesc = []byte{
	0x0a, 0x61, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d,
	0x30, 0x30, 0x35, 0x35, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x79, 0x61,
	0x72, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6e, 0x6d, 0x2f, 0x79, 0x61, 0x72,
	0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f,
	0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6e, 0x6d, 0x1a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2f, 0x67, 0x6f,
	0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x79, 0x61, 0x72, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x79, 0x61, 0x72, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbd, 0x04, 0x0a, 0x20, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x52, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x42, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f,
	0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x12, 0x5a, 0x0a, 0x04, 0x61, 0x63, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30,
	0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x43, 0x4c, 0x4d, 0x61,
	0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x61, 0x63, 0x6c, 0x73, 0x12, 0x82, 0x01, 0x0a,
	0x17, 0x6c, 0x6f, 0x67, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30,
	0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x6f, 0x67, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x15, 0x6c, 0x6f, 0x67, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x44, 0x0a, 0x1b, 0x61, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x02, 0x2d, 0x31, 0x52, 0x1b, 0x61, 0x70, 0x70, 0x4c,
	0x6f, 0x67, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x68, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x77, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35,
	0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x6e, 0x6d, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x8a, 0x02, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x64,
	0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x64, 0x69, 0x72,
	0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x64, 0x69, 0x72, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x64, 0x69, 0x72, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x49, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2c, 0x0a, 0x11, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0xaa,
	0x01, 0x0a, 0x16, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x5e, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35,
	0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x49, 0x0a, 0x0f, 0x4c,
	0x6f, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x10, 0x46, 0x6c, 0x6f, 0x77, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c,
	0x6f, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6c,
	0x6f, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x77, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6c, 0x6f,
	0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6c, 0x6f, 0x77,
	0x52, 0x75, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x6c, 0x6f,
	0x77, 0x52, 0x75, 0x6e, 0x49, 0x64, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2f, 0x67, 0x6f, 0x2d,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x79, 0x61, 0x72, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x6e, 0x6d,
}

var (
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescOnce sync.Once
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescData = file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDesc
)

func file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescGZIP() []byte {
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescOnce.Do(func() {
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescData)
	})
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDescData
}

var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_goTypes = []interface{}{
	(*ContainerManagerApplicationProto)(nil), // 0: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.ContainerManagerApplicationProto
	(*DeletionServiceDeleteTaskProto)(nil),   // 1: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.DeletionServiceDeleteTaskProto
	(*LocalizedResourceProto)(nil),           // 2: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.LocalizedResourceProto
	(*LogDeleterProto)(nil),                  // 3: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.LogDeleterProto
	(*FlowContextProto)(nil),                 // 4: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.FlowContextProto
	(*api.ApplicationIdProto)(nil),           // 5: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.ApplicationIdProto
	(*api.ApplicationACLMapProto)(nil),       // 6: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.ApplicationACLMapProto
	(*api.LogAggregationContextProto)(nil),   // 7: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.LogAggregationContextProto
	(*api.LocalResourceProto)(nil),           // 8: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.LocalResourceProto
}
var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_depIdxs = []int32{
	5, // 0: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.ContainerManagerApplicationProto.id:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.ApplicationIdProto
	6, // 1: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.ContainerManagerApplicationProto.acls:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.ApplicationACLMapProto
	7, // 2: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.ContainerManagerApplicationProto.log_aggregation_context:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.LogAggregationContextProto
	4, // 3: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.ContainerManagerApplicationProto.flowContext:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.FlowContextProto
	8, // 4: github.com.kom0055.go_hadoop.v1alpha1.yarn.server.nm.LocalizedResourceProto.resource:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.LocalResourceProto
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() {
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_init()
}
func file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_init() {
	if File_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerManagerApplicationProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletionServiceDeleteTaskProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalizedResourceProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogDeleterProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowContextProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_goTypes,
		DependencyIndexes: file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_depIdxs,
		MessageInfos:      file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_msgTypes,
	}.Build()
	File_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto = out.File
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_rawDesc = nil
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_goTypes = nil
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_server_nm_yarn_server_nodemanager_recovery_proto_depIdxs = nil
}
