//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: github.com/kom0055/go-hadoop/proto/v1alpha1/yarn/api/server/yarn_server_resourcemanager_service_protos.proto

package server

import (
	api "github.com/kom0055/go-hadoop/proto/v1alpha1/yarn/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecommissionTypeProto int32

const (
	DecommissionTypeProto_NORMAL   DecommissionTypeProto = 1
	DecommissionTypeProto_GRACEFUL DecommissionTypeProto = 2
	DecommissionTypeProto_FORCEFUL DecommissionTypeProto = 3
)

// Enum value maps for DecommissionTypeProto.
var (
	DecommissionTypeProto_name = map[int32]string{
		1: "NORMAL",
		2: "GRACEFUL",
		3: "FORCEFUL",
	}
	DecommissionTypeProto_value = map[string]int32{
		"NORMAL":   1,
		"GRACEFUL": 2,
		"FORCEFUL": 3,
	}
)

func (x DecommissionTypeProto) Enum() *DecommissionTypeProto {
	p := new(DecommissionTypeProto)
	*p = x
	return p
}

func (x DecommissionTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecommissionTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_enumTypes[0].Descriptor()
}

func (DecommissionTypeProto) Type() protoreflect.EnumType {
	return &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_enumTypes[0]
}

func (x DecommissionTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DecommissionTypeProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DecommissionTypeProto(num)
	return nil
}

// Deprecated: Use DecommissionTypeProto.Descriptor instead.
func (DecommissionTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{0}
}

type RefreshQueuesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshQueuesRequestProto) Reset() {
	*x = RefreshQueuesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshQueuesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshQueuesRequestProto) ProtoMessage() {}

func (x *RefreshQueuesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshQueuesRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshQueuesRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{0}
}

type RefreshQueuesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshQueuesResponseProto) Reset() {
	*x = RefreshQueuesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshQueuesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshQueuesResponseProto) ProtoMessage() {}

func (x *RefreshQueuesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshQueuesResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshQueuesResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{1}
}

type RefreshNodesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DecommissionType    *DecommissionTypeProto `protobuf:"varint,1,opt,name=decommissionType,enum=github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.DecommissionTypeProto,def=1" json:"decommissionType,omitempty"`
	DecommissionTimeout *int32                 `protobuf:"varint,2,opt,name=decommissionTimeout" json:"decommissionTimeout,omitempty"`
}

// Default values for RefreshNodesRequestProto fields.
const (
	Default_RefreshNodesRequestProto_DecommissionType = DecommissionTypeProto_NORMAL
)

func (x *RefreshNodesRequestProto) Reset() {
	*x = RefreshNodesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesRequestProto) ProtoMessage() {}

func (x *RefreshNodesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshNodesRequestProto) GetDecommissionType() DecommissionTypeProto {
	if x != nil && x.DecommissionType != nil {
		return *x.DecommissionType
	}
	return Default_RefreshNodesRequestProto_DecommissionType
}

func (x *RefreshNodesRequestProto) GetDecommissionTimeout() int32 {
	if x != nil && x.DecommissionTimeout != nil {
		return *x.DecommissionTimeout
	}
	return 0
}

type RefreshNodesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNodesResponseProto) Reset() {
	*x = RefreshNodesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesResponseProto) ProtoMessage() {}

func (x *RefreshNodesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{3}
}

type RefreshSuperUserGroupsConfigurationRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) Reset() {
	*x = RefreshSuperUserGroupsConfigurationRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSuperUserGroupsConfigurationRequestProto) ProtoMessage() {}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSuperUserGroupsConfigurationRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshSuperUserGroupsConfigurationRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{4}
}

type RefreshSuperUserGroupsConfigurationResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) Reset() {
	*x = RefreshSuperUserGroupsConfigurationResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSuperUserGroupsConfigurationResponseProto) ProtoMessage() {}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSuperUserGroupsConfigurationResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshSuperUserGroupsConfigurationResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{5}
}

type RefreshUserToGroupsMappingsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshUserToGroupsMappingsRequestProto) Reset() {
	*x = RefreshUserToGroupsMappingsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshUserToGroupsMappingsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUserToGroupsMappingsRequestProto) ProtoMessage() {}

func (x *RefreshUserToGroupsMappingsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUserToGroupsMappingsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshUserToGroupsMappingsRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{6}
}

type RefreshUserToGroupsMappingsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshUserToGroupsMappingsResponseProto) Reset() {
	*x = RefreshUserToGroupsMappingsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshUserToGroupsMappingsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUserToGroupsMappingsResponseProto) ProtoMessage() {}

func (x *RefreshUserToGroupsMappingsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUserToGroupsMappingsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshUserToGroupsMappingsResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{7}
}

type RefreshAdminAclsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAdminAclsRequestProto) Reset() {
	*x = RefreshAdminAclsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAdminAclsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminAclsRequestProto) ProtoMessage() {}

func (x *RefreshAdminAclsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminAclsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshAdminAclsRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{8}
}

type RefreshAdminAclsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshAdminAclsResponseProto) Reset() {
	*x = RefreshAdminAclsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAdminAclsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminAclsResponseProto) ProtoMessage() {}

func (x *RefreshAdminAclsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminAclsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshAdminAclsResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{9}
}

type RefreshServiceAclsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshServiceAclsRequestProto) Reset() {
	*x = RefreshServiceAclsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshServiceAclsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceAclsRequestProto) ProtoMessage() {}

func (x *RefreshServiceAclsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceAclsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshServiceAclsRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{10}
}

type RefreshServiceAclsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshServiceAclsResponseProto) Reset() {
	*x = RefreshServiceAclsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshServiceAclsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceAclsResponseProto) ProtoMessage() {}

func (x *RefreshServiceAclsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceAclsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshServiceAclsResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{11}
}

type GetGroupsForUserRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
}

func (x *GetGroupsForUserRequestProto) Reset() {
	*x = GetGroupsForUserRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsForUserRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserRequestProto) ProtoMessage() {}

func (x *GetGroupsForUserRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserRequestProto.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupsForUserRequestProto) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

type GetGroupsForUserResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (x *GetGroupsForUserResponseProto) Reset() {
	*x = GetGroupsForUserResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsForUserResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserResponseProto) ProtoMessage() {}

func (x *GetGroupsForUserResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserResponseProto.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupsForUserResponseProto) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type UpdateNodeResourceRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeResourceMap []*api.NodeResourceMapProto `protobuf:"bytes,1,rep,name=node_resource_map,json=nodeResourceMap" json:"node_resource_map,omitempty"`
}

func (x *UpdateNodeResourceRequestProto) Reset() {
	*x = UpdateNodeResourceRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeResourceRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeResourceRequestProto) ProtoMessage() {}

func (x *UpdateNodeResourceRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeResourceRequestProto.ProtoReflect.Descriptor instead.
func (*UpdateNodeResourceRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateNodeResourceRequestProto) GetNodeResourceMap() []*api.NodeResourceMapProto {
	if x != nil {
		return x.NodeResourceMap
	}
	return nil
}

type UpdateNodeResourceResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNodeResourceResponseProto) Reset() {
	*x = UpdateNodeResourceResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeResourceResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeResourceResponseProto) ProtoMessage() {}

func (x *UpdateNodeResourceResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeResourceResponseProto.ProtoReflect.Descriptor instead.
func (*UpdateNodeResourceResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{15}
}

type RefreshNodesResourcesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNodesResourcesRequestProto) Reset() {
	*x = RefreshNodesResourcesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesResourcesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesResourcesRequestProto) ProtoMessage() {}

func (x *RefreshNodesResourcesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesResourcesRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesResourcesRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{16}
}

type RefreshNodesResourcesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNodesResourcesResponseProto) Reset() {
	*x = RefreshNodesResourcesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNodesResourcesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNodesResourcesResponseProto) ProtoMessage() {}

func (x *RefreshNodesResourcesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNodesResourcesResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshNodesResourcesResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{17}
}

type AddToClusterNodeLabelsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeprecatedNodeLabels []string              `protobuf:"bytes,1,rep,name=deprecatedNodeLabels" json:"deprecatedNodeLabels,omitempty"`
	NodeLabels           []*api.NodeLabelProto `protobuf:"bytes,2,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
}

func (x *AddToClusterNodeLabelsRequestProto) Reset() {
	*x = AddToClusterNodeLabelsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToClusterNodeLabelsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToClusterNodeLabelsRequestProto) ProtoMessage() {}

func (x *AddToClusterNodeLabelsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToClusterNodeLabelsRequestProto.ProtoReflect.Descriptor instead.
func (*AddToClusterNodeLabelsRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{18}
}

func (x *AddToClusterNodeLabelsRequestProto) GetDeprecatedNodeLabels() []string {
	if x != nil {
		return x.DeprecatedNodeLabels
	}
	return nil
}

func (x *AddToClusterNodeLabelsRequestProto) GetNodeLabels() []*api.NodeLabelProto {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

type AddToClusterNodeLabelsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddToClusterNodeLabelsResponseProto) Reset() {
	*x = AddToClusterNodeLabelsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToClusterNodeLabelsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToClusterNodeLabelsResponseProto) ProtoMessage() {}

func (x *AddToClusterNodeLabelsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToClusterNodeLabelsResponseProto.ProtoReflect.Descriptor instead.
func (*AddToClusterNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{19}
}

type RemoveFromClusterNodeLabelsRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeLabels []string `protobuf:"bytes,1,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
}

func (x *RemoveFromClusterNodeLabelsRequestProto) Reset() {
	*x = RemoveFromClusterNodeLabelsRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromClusterNodeLabelsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromClusterNodeLabelsRequestProto) ProtoMessage() {}

func (x *RemoveFromClusterNodeLabelsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromClusterNodeLabelsRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveFromClusterNodeLabelsRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveFromClusterNodeLabelsRequestProto) GetNodeLabels() []string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

type RemoveFromClusterNodeLabelsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveFromClusterNodeLabelsResponseProto) Reset() {
	*x = RemoveFromClusterNodeLabelsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromClusterNodeLabelsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromClusterNodeLabelsResponseProto) ProtoMessage() {}

func (x *RemoveFromClusterNodeLabelsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromClusterNodeLabelsResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveFromClusterNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{21}
}

type ReplaceLabelsOnNodeRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeToLabels       []*api.NodeIdToLabelsProto `protobuf:"bytes,1,rep,name=nodeToLabels" json:"nodeToLabels,omitempty"`
	FailOnUnknownNodes *bool                      `protobuf:"varint,2,opt,name=failOnUnknownNodes" json:"failOnUnknownNodes,omitempty"`
}

func (x *ReplaceLabelsOnNodeRequestProto) Reset() {
	*x = ReplaceLabelsOnNodeRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceLabelsOnNodeRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceLabelsOnNodeRequestProto) ProtoMessage() {}

func (x *ReplaceLabelsOnNodeRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceLabelsOnNodeRequestProto.ProtoReflect.Descriptor instead.
func (*ReplaceLabelsOnNodeRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{22}
}

func (x *ReplaceLabelsOnNodeRequestProto) GetNodeToLabels() []*api.NodeIdToLabelsProto {
	if x != nil {
		return x.NodeToLabels
	}
	return nil
}

func (x *ReplaceLabelsOnNodeRequestProto) GetFailOnUnknownNodes() bool {
	if x != nil && x.FailOnUnknownNodes != nil {
		return *x.FailOnUnknownNodes
	}
	return false
}

type ReplaceLabelsOnNodeResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplaceLabelsOnNodeResponseProto) Reset() {
	*x = ReplaceLabelsOnNodeResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplaceLabelsOnNodeResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceLabelsOnNodeResponseProto) ProtoMessage() {}

func (x *ReplaceLabelsOnNodeResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceLabelsOnNodeResponseProto.ProtoReflect.Descriptor instead.
func (*ReplaceLabelsOnNodeResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{23}
}

type UpdateNodeLabelsResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNodeLabelsResponseProto) Reset() {
	*x = UpdateNodeLabelsResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeLabelsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeLabelsResponseProto) ProtoMessage() {}

func (x *UpdateNodeLabelsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeLabelsResponseProto.ProtoReflect.Descriptor instead.
func (*UpdateNodeLabelsResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{24}
}

type CheckForDecommissioningNodesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckForDecommissioningNodesRequestProto) Reset() {
	*x = CheckForDecommissioningNodesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckForDecommissioningNodesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForDecommissioningNodesRequestProto) ProtoMessage() {}

func (x *CheckForDecommissioningNodesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForDecommissioningNodesRequestProto.ProtoReflect.Descriptor instead.
func (*CheckForDecommissioningNodesRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{25}
}

type CheckForDecommissioningNodesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DecommissioningNodes []*api.NodeIdProto `protobuf:"bytes,1,rep,name=decommissioningNodes" json:"decommissioningNodes,omitempty"`
}

func (x *CheckForDecommissioningNodesResponseProto) Reset() {
	*x = CheckForDecommissioningNodesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckForDecommissioningNodesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForDecommissioningNodesResponseProto) ProtoMessage() {}

func (x *CheckForDecommissioningNodesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForDecommissioningNodesResponseProto.ProtoReflect.Descriptor instead.
func (*CheckForDecommissioningNodesResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{26}
}

func (x *CheckForDecommissioningNodesResponseProto) GetDecommissioningNodes() []*api.NodeIdProto {
	if x != nil {
		return x.DecommissioningNodes
	}
	return nil
}

type RefreshClusterMaxPriorityRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshClusterMaxPriorityRequestProto) Reset() {
	*x = RefreshClusterMaxPriorityRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshClusterMaxPriorityRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshClusterMaxPriorityRequestProto) ProtoMessage() {}

func (x *RefreshClusterMaxPriorityRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshClusterMaxPriorityRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshClusterMaxPriorityRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{27}
}

type RefreshClusterMaxPriorityResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshClusterMaxPriorityResponseProto) Reset() {
	*x = RefreshClusterMaxPriorityResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshClusterMaxPriorityResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshClusterMaxPriorityResponseProto) ProtoMessage() {}

func (x *RefreshClusterMaxPriorityResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshClusterMaxPriorityResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshClusterMaxPriorityResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{28}
}

type NodeIdToLabelsNameProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     *api.NodeIdProto `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
	NodeLabels []string         `protobuf:"bytes,2,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
}

func (x *NodeIdToLabelsNameProto) Reset() {
	*x = NodeIdToLabelsNameProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeIdToLabelsNameProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdToLabelsNameProto) ProtoMessage() {}

func (x *NodeIdToLabelsNameProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdToLabelsNameProto.ProtoReflect.Descriptor instead.
func (*NodeIdToLabelsNameProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{29}
}

func (x *NodeIdToLabelsNameProto) GetNodeId() *api.NodeIdProto {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *NodeIdToLabelsNameProto) GetNodeLabels() []string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

// ////////////////////////////////////////////////////////////////
// /////////// RM Failover related records ////////////////////////
// ////////////////////////////////////////////////////////////////
type ActiveRMInfoProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId *string `protobuf:"bytes,1,opt,name=clusterId" json:"clusterId,omitempty"`
	RmId      *string `protobuf:"bytes,2,opt,name=rmId" json:"rmId,omitempty"`
}

func (x *ActiveRMInfoProto) Reset() {
	*x = ActiveRMInfoProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveRMInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRMInfoProto) ProtoMessage() {}

func (x *ActiveRMInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRMInfoProto.ProtoReflect.Descriptor instead.
func (*ActiveRMInfoProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP(), []int{30}
}

func (x *ActiveRMInfoProto) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

func (x *ActiveRMInfoProto) GetRmId() string {
	if x != nil && x.RmId != nil {
		return *x.RmId
	}
	return ""
}

var File_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto protoreflect.FileDescriptor

var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDesc = []byte{
	0x0a, 0x6c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d,
	0x30, 0x30, 0x35, 0x35, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x79, 0x61,
	0x72, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x79, 0x61,
	0x72, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x35,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30,
	0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x61, 0x64,
	0x6f, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2f, 0x79, 0x61, 0x72, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x79, 0x61, 0x72, 0x6e,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a,
	0x19, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x80, 0x01, 0x0a, 0x10, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x4c, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f,
	0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x3a, 0x06,
	0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x52, 0x10, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x64, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x2f, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x53, 0x75, 0x70, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x30, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x53, 0x75, 0x70, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29,
	0x0a, 0x27, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x28, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x1e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x1f, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x37, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x46, 0x6f, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x1e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x70, 0x0a, 0x11, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68,
	0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79,
	0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0f, 0x6e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x22, 0x21, 0x0a,
	0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x23, 0x0a, 0x21, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x22, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x22,
	0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x32, 0x0a, 0x14, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x14, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x5e, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e,
	0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x25, 0x0a, 0x23, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a,
	0x27, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f,
	0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x2a, 0x0a, 0x28, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64,
	0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x1f, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x4f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x67, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65,
	0x54, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x43,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30,
	0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x54, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x2e, 0x0a, 0x12, 0x66, 0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x66,
	0x61, 0x69, 0x6c, 0x4f, 0x6e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x22, 0x0a, 0x20, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x4f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x28, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46,
	0x6f, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e,
	0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x29, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x6f, 0x72, 0x44,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x6f, 0x0a, 0x14, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30,
	0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x14, 0x64, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x27, 0x0a, 0x25, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x26, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x78, 0x50,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x17, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x54,
	0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x53, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3b, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f,
	0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x79, 0x61, 0x72, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x45, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52,
	0x4d, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6d, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6d, 0x49, 0x64, 0x2a, 0x3f, 0x0a, 0x15,
	0x44, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x52, 0x41, 0x43, 0x45, 0x46, 0x55, 0x4c, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x46, 0x55, 0x4c, 0x10, 0x03, 0x42, 0x3d, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d, 0x30,
	0x30, 0x35, 0x35, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x79, 0x61, 0x72,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
}

var (
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescOnce sync.Once
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescData = file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDesc
)

func file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescGZIP() []byte {
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescOnce.Do(func() {
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescData)
	})
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDescData
}

var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_goTypes = []interface{}{
	(DecommissionTypeProto)(0),                               // 0: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.DecommissionTypeProto
	(*RefreshQueuesRequestProto)(nil),                        // 1: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshQueuesRequestProto
	(*RefreshQueuesResponseProto)(nil),                       // 2: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshQueuesResponseProto
	(*RefreshNodesRequestProto)(nil),                         // 3: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshNodesRequestProto
	(*RefreshNodesResponseProto)(nil),                        // 4: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshNodesResponseProto
	(*RefreshSuperUserGroupsConfigurationRequestProto)(nil),  // 5: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshSuperUserGroupsConfigurationRequestProto
	(*RefreshSuperUserGroupsConfigurationResponseProto)(nil), // 6: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshSuperUserGroupsConfigurationResponseProto
	(*RefreshUserToGroupsMappingsRequestProto)(nil),          // 7: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshUserToGroupsMappingsRequestProto
	(*RefreshUserToGroupsMappingsResponseProto)(nil),         // 8: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshUserToGroupsMappingsResponseProto
	(*RefreshAdminAclsRequestProto)(nil),                     // 9: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshAdminAclsRequestProto
	(*RefreshAdminAclsResponseProto)(nil),                    // 10: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshAdminAclsResponseProto
	(*RefreshServiceAclsRequestProto)(nil),                   // 11: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshServiceAclsRequestProto
	(*RefreshServiceAclsResponseProto)(nil),                  // 12: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshServiceAclsResponseProto
	(*GetGroupsForUserRequestProto)(nil),                     // 13: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.GetGroupsForUserRequestProto
	(*GetGroupsForUserResponseProto)(nil),                    // 14: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.GetGroupsForUserResponseProto
	(*UpdateNodeResourceRequestProto)(nil),                   // 15: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.UpdateNodeResourceRequestProto
	(*UpdateNodeResourceResponseProto)(nil),                  // 16: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.UpdateNodeResourceResponseProto
	(*RefreshNodesResourcesRequestProto)(nil),                // 17: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshNodesResourcesRequestProto
	(*RefreshNodesResourcesResponseProto)(nil),               // 18: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshNodesResourcesResponseProto
	(*AddToClusterNodeLabelsRequestProto)(nil),               // 19: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.AddToClusterNodeLabelsRequestProto
	(*AddToClusterNodeLabelsResponseProto)(nil),              // 20: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.AddToClusterNodeLabelsResponseProto
	(*RemoveFromClusterNodeLabelsRequestProto)(nil),          // 21: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RemoveFromClusterNodeLabelsRequestProto
	(*RemoveFromClusterNodeLabelsResponseProto)(nil),         // 22: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RemoveFromClusterNodeLabelsResponseProto
	(*ReplaceLabelsOnNodeRequestProto)(nil),                  // 23: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.ReplaceLabelsOnNodeRequestProto
	(*ReplaceLabelsOnNodeResponseProto)(nil),                 // 24: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.ReplaceLabelsOnNodeResponseProto
	(*UpdateNodeLabelsResponseProto)(nil),                    // 25: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.UpdateNodeLabelsResponseProto
	(*CheckForDecommissioningNodesRequestProto)(nil),         // 26: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.CheckForDecommissioningNodesRequestProto
	(*CheckForDecommissioningNodesResponseProto)(nil),        // 27: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.CheckForDecommissioningNodesResponseProto
	(*RefreshClusterMaxPriorityRequestProto)(nil),            // 28: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshClusterMaxPriorityRequestProto
	(*RefreshClusterMaxPriorityResponseProto)(nil),           // 29: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshClusterMaxPriorityResponseProto
	(*NodeIdToLabelsNameProto)(nil),                          // 30: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.NodeIdToLabelsNameProto
	(*ActiveRMInfoProto)(nil),                                // 31: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.ActiveRMInfoProto
	(*api.NodeResourceMapProto)(nil),                         // 32: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeResourceMapProto
	(*api.NodeLabelProto)(nil),                               // 33: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeLabelProto
	(*api.NodeIdToLabelsProto)(nil),                          // 34: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeIdToLabelsProto
	(*api.NodeIdProto)(nil),                                  // 35: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeIdProto
}
var file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_depIdxs = []int32{
	0,  // 0: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.RefreshNodesRequestProto.decommissionType:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.DecommissionTypeProto
	32, // 1: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.UpdateNodeResourceRequestProto.node_resource_map:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeResourceMapProto
	33, // 2: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.AddToClusterNodeLabelsRequestProto.nodeLabels:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeLabelProto
	34, // 3: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.ReplaceLabelsOnNodeRequestProto.nodeToLabels:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeIdToLabelsProto
	35, // 4: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.CheckForDecommissioningNodesResponseProto.decommissioningNodes:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeIdProto
	35, // 5: github.com.kom0055.go_hadoop.v1alpha1.yarn.api.server.NodeIdToLabelsNameProto.nodeId:type_name -> github.com.kom0055.go_hadoop.v1alpha1.yarn.api.NodeIdProto
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() {
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_init()
}
func file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_init() {
	if File_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshQueuesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshQueuesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshSuperUserGroupsConfigurationRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshSuperUserGroupsConfigurationResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshUserToGroupsMappingsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshUserToGroupsMappingsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAdminAclsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAdminAclsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshServiceAclsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshServiceAclsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsForUserRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsForUserResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeResourceRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeResourceResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesResourcesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNodesResourcesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToClusterNodeLabelsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToClusterNodeLabelsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromClusterNodeLabelsRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromClusterNodeLabelsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceLabelsOnNodeRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplaceLabelsOnNodeResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeLabelsResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckForDecommissioningNodesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckForDecommissioningNodesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshClusterMaxPriorityRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshClusterMaxPriorityResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeIdToLabelsNameProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveRMInfoProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_goTypes,
		DependencyIndexes: file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_depIdxs,
		EnumInfos:         file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_enumTypes,
		MessageInfos:      file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_msgTypes,
	}.Build()
	File_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto = out.File
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_rawDesc = nil
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_goTypes = nil
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_yarn_api_server_yarn_server_resourcemanager_service_protos_proto_depIdxs = nil
}
