//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// This file contains protocol buffers that are used throughout HDFS -- i.e.
// by the client, server, and data transfer protocols.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: github.com/kom0055/go-hadoop/proto/v1alpha1/hdfs/JournalProtocol.proto

package hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Journal information used by the journal receiver to identify a journal.
type JournalInfoProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterID     *string `protobuf:"bytes,1,req,name=clusterID" json:"clusterID,omitempty"`          // ID of the cluster
	LayoutVersion *uint32 `protobuf:"varint,2,opt,name=layoutVersion" json:"layoutVersion,omitempty"` // Layout version
	NamespaceID   *uint32 `protobuf:"varint,3,opt,name=namespaceID" json:"namespaceID,omitempty"`     // Namespace ID
}

func (x *JournalInfoProto) Reset() {
	*x = JournalInfoProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JournalInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalInfoProto) ProtoMessage() {}

func (x *JournalInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalInfoProto.ProtoReflect.Descriptor instead.
func (*JournalInfoProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *JournalInfoProto) GetClusterID() string {
	if x != nil && x.ClusterID != nil {
		return *x.ClusterID
	}
	return ""
}

func (x *JournalInfoProto) GetLayoutVersion() uint32 {
	if x != nil && x.LayoutVersion != nil {
		return *x.LayoutVersion
	}
	return 0
}

func (x *JournalInfoProto) GetNamespaceID() uint32 {
	if x != nil && x.NamespaceID != nil {
		return *x.NamespaceID
	}
	return 0
}

// *
// journalInfo - the information about the journal
// firstTxnId - the first txid in the journal records
// numTxns - Number of transactions in editlog
// records - bytes containing serialized journal records
// epoch - change to this represents change of journal writer
type JournalRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JournalInfo *JournalInfoProto `protobuf:"bytes,1,req,name=journalInfo" json:"journalInfo,omitempty"`
	FirstTxnId  *uint64           `protobuf:"varint,2,req,name=firstTxnId" json:"firstTxnId,omitempty"`
	NumTxns     *uint32           `protobuf:"varint,3,req,name=numTxns" json:"numTxns,omitempty"`
	Records     []byte            `protobuf:"bytes,4,req,name=records" json:"records,omitempty"`
	Epoch       *uint64           `protobuf:"varint,5,req,name=epoch" json:"epoch,omitempty"`
}

func (x *JournalRequestProto) Reset() {
	*x = JournalRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JournalRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalRequestProto) ProtoMessage() {}

func (x *JournalRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalRequestProto.ProtoReflect.Descriptor instead.
func (*JournalRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *JournalRequestProto) GetJournalInfo() *JournalInfoProto {
	if x != nil {
		return x.JournalInfo
	}
	return nil
}

func (x *JournalRequestProto) GetFirstTxnId() uint64 {
	if x != nil && x.FirstTxnId != nil {
		return *x.FirstTxnId
	}
	return 0
}

func (x *JournalRequestProto) GetNumTxns() uint32 {
	if x != nil && x.NumTxns != nil {
		return *x.NumTxns
	}
	return 0
}

func (x *JournalRequestProto) GetRecords() []byte {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *JournalRequestProto) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

// *
// void response
type JournalResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JournalResponseProto) Reset() {
	*x = JournalResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JournalResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalResponseProto) ProtoMessage() {}

func (x *JournalResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalResponseProto.ProtoReflect.Descriptor instead.
func (*JournalResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP(), []int{2}
}

// *
// journalInfo - the information about the journal
// txid - first txid in the new log
type StartLogSegmentRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JournalInfo *JournalInfoProto `protobuf:"bytes,1,req,name=journalInfo" json:"journalInfo,omitempty"` // Info about the journal
	Txid        *uint64           `protobuf:"varint,2,req,name=txid" json:"txid,omitempty"`              // Transaction ID
	Epoch       *uint64           `protobuf:"varint,3,req,name=epoch" json:"epoch,omitempty"`
}

func (x *StartLogSegmentRequestProto) Reset() {
	*x = StartLogSegmentRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLogSegmentRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLogSegmentRequestProto) ProtoMessage() {}

func (x *StartLogSegmentRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLogSegmentRequestProto.ProtoReflect.Descriptor instead.
func (*StartLogSegmentRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *StartLogSegmentRequestProto) GetJournalInfo() *JournalInfoProto {
	if x != nil {
		return x.JournalInfo
	}
	return nil
}

func (x *StartLogSegmentRequestProto) GetTxid() uint64 {
	if x != nil && x.Txid != nil {
		return *x.Txid
	}
	return 0
}

func (x *StartLogSegmentRequestProto) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

// *
// void response
type StartLogSegmentResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartLogSegmentResponseProto) Reset() {
	*x = StartLogSegmentResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLogSegmentResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLogSegmentResponseProto) ProtoMessage() {}

func (x *StartLogSegmentResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLogSegmentResponseProto.ProtoReflect.Descriptor instead.
func (*StartLogSegmentResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP(), []int{4}
}

// *
// journalInfo - the information about the journal
// txid - first txid in the new log
type FenceRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JournalInfo *JournalInfoProto `protobuf:"bytes,1,req,name=journalInfo" json:"journalInfo,omitempty"` // Info about the journal
	Epoch       *uint64           `protobuf:"varint,2,req,name=epoch" json:"epoch,omitempty"`            // Epoch - change indicates change in writer
	FencerInfo  *string           `protobuf:"bytes,3,opt,name=fencerInfo" json:"fencerInfo,omitempty"`   // Info about fencer for debugging
}

func (x *FenceRequestProto) Reset() {
	*x = FenceRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FenceRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceRequestProto) ProtoMessage() {}

func (x *FenceRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceRequestProto.ProtoReflect.Descriptor instead.
func (*FenceRequestProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP(), []int{5}
}

func (x *FenceRequestProto) GetJournalInfo() *JournalInfoProto {
	if x != nil {
		return x.JournalInfo
	}
	return nil
}

func (x *FenceRequestProto) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *FenceRequestProto) GetFencerInfo() string {
	if x != nil && x.FencerInfo != nil {
		return *x.FencerInfo
	}
	return ""
}

// *
// previousEpoch - previous epoch if any or zero
// lastTransactionId - last valid transaction Id in the journal
// inSync - if all journal segments are available and in sync
type FenceResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviousEpoch     *uint64 `protobuf:"varint,1,opt,name=previousEpoch" json:"previousEpoch,omitempty"`
	LastTransactionId *uint64 `protobuf:"varint,2,opt,name=lastTransactionId" json:"lastTransactionId,omitempty"`
	InSync            *bool   `protobuf:"varint,3,opt,name=inSync" json:"inSync,omitempty"`
}

func (x *FenceResponseProto) Reset() {
	*x = FenceResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FenceResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceResponseProto) ProtoMessage() {}

func (x *FenceResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceResponseProto.ProtoReflect.Descriptor instead.
func (*FenceResponseProto) Descriptor() ([]byte, []int) {
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP(), []int{6}
}

func (x *FenceResponseProto) GetPreviousEpoch() uint64 {
	if x != nil && x.PreviousEpoch != nil {
		return *x.PreviousEpoch
	}
	return 0
}

func (x *FenceResponseProto) GetLastTransactionId() uint64 {
	if x != nil && x.LastTransactionId != nil {
		return *x.LastTransactionId
	}
	return 0
}

func (x *FenceResponseProto) GetInSync() bool {
	if x != nil && x.InSync != nil {
		return *x.InSync
	}
	return false
}

var File_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto protoreflect.FileDescriptor

var file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDesc = []byte{
	0x0a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d,
	0x30, 0x30, 0x35, 0x35, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x68, 0x64,
	0x66, 0x73, 0x2f, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x68, 0x64, 0x66, 0x73, 0x22, 0x78, 0x0a, 0x10, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x22, 0xdf,
	0x01, 0x0a, 0x13, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x5e, 0x0a, 0x0b, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35,
	0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x6a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x54,
	0x78, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x54, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x54, 0x78, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x54, 0x78, 0x6e, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x18, 0x05, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x22, 0x16, 0x0a, 0x14, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x1b, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x5e, 0x0a, 0x0b, 0x6a, 0x6f, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x3c, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30,
	0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x6a, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x11, 0x46, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x5e, 0x0a, 0x0b, 0x6a, 0x6f, 0x75, 0x72,
	0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x3c, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30,
	0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x6a, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63,
	0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1e,
	0x0a, 0x0a, 0x66, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x80,
	0x01, 0x0a, 0x12, 0x46, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75,
	0x73, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x70, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x2c, 0x0a, 0x11, 0x6c,
	0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x53,
	0x79, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x53, 0x79, 0x6e,
	0x63, 0x32, 0xd7, 0x03, 0x0a, 0x16, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x8c, 0x01, 0x0a,
	0x07, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x3f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f,
	0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x40, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67,
	0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0xa4, 0x01, 0x0a, 0x0f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x47, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d,
	0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x48, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35, 0x2e, 0x67, 0x6f,
	0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x86, 0x01, 0x0a, 0x05, 0x66, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x3d, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35,
	0x35, 0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x46, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3e, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35, 0x35,
	0x2e, 0x67, 0x6f, 0x5f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x46, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6d, 0x30, 0x30, 0x35,
	0x35, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x68, 0x64, 0x66, 0x73,
}

var (
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescOnce sync.Once
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescData = file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDesc
)

func file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescGZIP() []byte {
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescOnce.Do(func() {
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescData)
	})
	return file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDescData
}

var file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_goTypes = []interface{}{
	(*JournalInfoProto)(nil),             // 0: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalInfoProto
	(*JournalRequestProto)(nil),          // 1: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalRequestProto
	(*JournalResponseProto)(nil),         // 2: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalResponseProto
	(*StartLogSegmentRequestProto)(nil),  // 3: github.com.kom0055.go_hadoop.v1alpha1.hdfs.StartLogSegmentRequestProto
	(*StartLogSegmentResponseProto)(nil), // 4: github.com.kom0055.go_hadoop.v1alpha1.hdfs.StartLogSegmentResponseProto
	(*FenceRequestProto)(nil),            // 5: github.com.kom0055.go_hadoop.v1alpha1.hdfs.FenceRequestProto
	(*FenceResponseProto)(nil),           // 6: github.com.kom0055.go_hadoop.v1alpha1.hdfs.FenceResponseProto
}
var file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_depIdxs = []int32{
	0, // 0: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalRequestProto.journalInfo:type_name -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalInfoProto
	0, // 1: github.com.kom0055.go_hadoop.v1alpha1.hdfs.StartLogSegmentRequestProto.journalInfo:type_name -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalInfoProto
	0, // 2: github.com.kom0055.go_hadoop.v1alpha1.hdfs.FenceRequestProto.journalInfo:type_name -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalInfoProto
	1, // 3: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalProtocolService.journal:input_type -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalRequestProto
	3, // 4: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalProtocolService.startLogSegment:input_type -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.StartLogSegmentRequestProto
	5, // 5: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalProtocolService.fence:input_type -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.FenceRequestProto
	2, // 6: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalProtocolService.journal:output_type -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalResponseProto
	4, // 7: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalProtocolService.startLogSegment:output_type -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.StartLogSegmentResponseProto
	6, // 8: github.com.kom0055.go_hadoop.v1alpha1.hdfs.JournalProtocolService.fence:output_type -> github.com.kom0055.go_hadoop.v1alpha1.hdfs.FenceResponseProto
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_init() }
func file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_init() {
	if File_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JournalInfoProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JournalRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JournalResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartLogSegmentRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartLogSegmentResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FenceRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FenceResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_goTypes,
		DependencyIndexes: file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_depIdxs,
		MessageInfos:      file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_msgTypes,
	}.Build()
	File_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto = out.File
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_rawDesc = nil
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_goTypes = nil
	file_github_com_kom0055_go_hadoop_proto_v1alpha1_hdfs_JournalProtocol_proto_depIdxs = nil
}
